"""store answer prompt version

Revision ID: f45fbfc41a14
Revises: 524d749334c8
Create Date: 2026-07-31 19:05:57.860195

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f45fbfc41a14"
down_revision: str | Sequence[str] | None = "524d749334c8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_answers",
        sa.Column("prompt_version", sa.String(length=80), server_default="unknown", nullable=False),
    )
    op.alter_column("document_answers", "prompt_version", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_answers", "prompt_version")
    # ### end Alembic commands ###
